# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 09:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hands_id', models.CharField(default='', max_length=20)),
                ('consume_gold', models.IntegerField(default=0)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('gold', models.IntegerField(default=0)),
                ('avatar', models.CharField(default='', max_length=500, null=True)),
                ('token', models.CharField(default='', max_length=500)),
                ('unionid', models.CharField(default='', max_length=500, null=True)),
                ('login_type', models.IntegerField(choices=[(0, '微信登陆'), (1, 'qq登陆')], default=0)),
                ('version', models.IntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'kuaishou_client',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(default='撒打算的', max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin_id',
            },
        ),
        migrations.CreateModel(
            name='CheckVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=1, max_length=100)),
                ('sdk_url', models.CharField(default='1', max_length=500)),
                ('update_msg', models.CharField(default='1', max_length=1000)),
            ],
            options={
                'db_table': 'version_num',
            },
        ),
        migrations.CreateModel(
            name='Combo_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('count_project', models.IntegerField(default=0)),
                ('pro_gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, null=True, verbose_name='积分')),
            ],
            options={
                'db_table': 'combo_project',
            },
        ),
        migrations.CreateModel(
            name='Old_Order_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='积分')),
            ],
            options={
                'db_table': 'kuaishou_expend_ord',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='积分')),
                ('data', models.TextField(default='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('showdata', models.TextField(default='')),
                ('count_init', models.IntegerField(default=0)),
                ('type_id', models.IntegerField(default=0)),
                ('kuaishou_id', models.CharField(default='', max_length=20)),
                ('link_works', models.URLField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(0, '所有类型'), (1, '未开始'), (2, '执行中'), (3, '已完成'), (4, '异常单'), (5, '已撤单')], default=1)),
                ('order_id_num', models.CharField(max_length=2000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kuaishou_order',
            },
        ),
        migrations.CreateModel(
            name='Order_combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pro_gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='积分')),
            ],
            options={
                'db_table': 'kuaishou_combo',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('count_project', models.IntegerField(default=0)),
                ('pro_gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, null=True, verbose_name='积分')),
                ('pro_type', models.IntegerField(choices=[(1, '刷粉丝'), (2, '刷双击'), (3, '刷播放')], default=1)),
            ],
            options={
                'db_table': 'kuaishou_project',
            },
        ),
        migrations.AddField(
            model_name='order_combo',
            name='detail_combo',
            field=models.ManyToManyField(blank=True, to='kuaishou_admin.Project'),
        ),
        migrations.AddField(
            model_name='order_combo',
            name='project_detail',
            field=models.ManyToManyField(to='kuaishou_admin.Combo_project'),
        ),
        migrations.AddField(
            model_name='order',
            name='combo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='kuaishou_admin.Order_combo'),
        ),
        migrations.AddField(
            model_name='order',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='kuaishou_admin.Project'),
        ),
        migrations.AddField(
            model_name='old_order_project',
            name='orders',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kuaishou_admin.Order'),
        ),
    ]
