# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmanagement',
            name='wechat',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
