# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 06:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(default='', max_length=500)),
                ('third_name', models.CharField(default='', max_length=20)),
                ('app_id', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'third_from',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=500, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='version',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loginfrom',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
