# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 21:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAndGold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='积分')),
                ('money', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='金钱')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='pro_type',
        ),
        migrations.AlterField(
            model_name='adminmanagement',
            name='wechat',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
