# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0002_auto_20180322_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pro_type',
        ),
    ]
