# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0002_auto_20180327_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='unionid',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
