# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 02:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0005_auto_20180316_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_project', models.IntegerField(default=0)),
                ('pro_gold', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, null=True, verbose_name='积分')),
            ],
            options={
                'db_table': 'combo_project',
            },
        ),
        migrations.AddField(
            model_name='order_combo',
            name='project_detail',
            field=models.ManyToManyField(to='kuaishou_admin.Combo_project'),
        ),
    ]
