# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_admin', '0006_auto_20180319_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo_project',
            old_name='name',
            new_name='pro_name',
        ),
    ]
