# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 09:58
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, verbose_name='订单号')),
                ('ddh', models.CharField(default='', max_length=100, verbose_name='支付平台订单号')),
                ('money', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='支付金额')),
                ('pay_list_date', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.IntegerField(choices=[(0, '积分充值'), (1, '开通会员')], default=0, verbose_name='订单类型')),
                ('pay_type', models.IntegerField(choices=[(0, '支付宝支付'), (1, '微信支付')], default=1, verbose_name='支付类型')),
                ('remark', models.TextField(default='', verbose_name='说明')),
                ('status', models.IntegerField(choices=[(1, '成功'), (2, '失败'), (3, '等待付款')], default=3, verbose_name='订单状态')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaveOpenId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(default='', max_length=500, null=True)),
                ('open_type', models.IntegerField(choices=[(0, '微信登录'), (1, 'QQ登录')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
