# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 02:09
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveopenid',
            name='client',
        ),
        migrations.AddField(
            model_name='paylistmodel',
            name='Amount_money',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='支付金额'),
        ),
        migrations.AddField(
            model_name='paylistmodel',
            name='trade_no',
            field=models.CharField(default='', max_length=200, verbose_name='支付宝流水号'),
        ),
        migrations.DeleteModel(
            name='SaveOpenId',
        ),
    ]
