# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 06:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaishou_app', '0003_auto_20180329_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylistmodel',
            name='Amount_money',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19, verbose_name='用户真正支付金额'),
        ),
    ]
